name: Delete
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:  # 添加这行来启用手动触发
  
jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete
        uses: xiaomeng9597/delete-workflow-runs@main
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 30
